modLoader = "kotlinforforge"
loaderVersion = "[1.6,1.11.0),[1.11.1,)"
license = "LGPL-3.0"

[[mods]]
modId = "ingameime"
version = "${version}"
displayName = "ContingameIME"
displayURL = "https://github.com/TexTrueStudio/IngameIME-ReInput"
logoFile = "icon.png"
credits = "Windmill_City"
authors = "ThinkingStudio, TexTrue, Wybxc"
description = '''
An unofficial continuation of IngameIME.

Enable IME in FullScreen Minecraft
'''

[[dependencies.ingameime]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ingameime]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ingameime]]
modId = "architectury"
mandatory = true
versionRange = "[5,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ingameime]]
modId = "cloth_config"
mandatory = true
versionRange = "[8,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.ingameime]]
modId = "roughlyenoughitems"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "CLIENT"
